version: '3.1'

services:
  db:
    image: mysql:5.5
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./app/sql:/docker-entrypoint-initdb.d/
  php:
    build: .
    command: bash -c "php -S 0.0.0.0:8080"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/code:z
    stdin_open: true
    tty: true
