AlAms:
  tableName: al_ams
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    analysis_id:
      type: integer
      unsigned: true
    al_ams_std_id:
      type: integer
      unsigned: true
    ams_lab_id:
      type: integer
      unsigned: true
    date:
      type: date(25)
    lab_num:
      type: string(255)
    r_to_rstd:
      type: double(53,30)
    interror:
      type: double(53,30)
    exterror:
      type: double(53,30)
    truefrac:
      type: double(53,30)
    notes:
      type: string(700)
  relations:
    Analysis:
      local: analysis_id
      foreign: id
      type: one
    AlAmsStd:
      local: al_ams_std_id
      foreign: id
      type: one
    AmsLab:
      local: ams_lab_id
      foreign: id
      type: one
    AmsCurrent:
      local: id
      foreign: al_ams_id
      type: many
AlAmsStd:
  tableName: al_ams_std
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(255)
    al_std_series_id:
      type: integer
      unsigned: true
    r26to27:
      type: double(53,30)
    error:
      type: double(53,30)
    notes:
      type: string
  relations:
    AlStdSeries:
      local: al_std_series_id
      foreign: id
      type: one
    AlAms:
      local: id
      foreign: al_ams_std_id
      type: many
AlCarrier:
  tableName: al_carrier
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string
      notnull: true
    al_conc:
      type: double(53,30)
    del_al_conc:
      type: double(53,30)
    r26to27:
      type: double(53,30)
    r26to27_error:
      type: double(53,30)
    in_service_date:
      type: date(25)
    mfg_lot_no:
      type: string
    owner:
      type: string
    notes:
      type: string
    in_use:
      type: string
  relations:
    Batch:
      local: id
      foreign: al_carrier_id
      type: many
AlStdSeries:
  tableName: al_std_series
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    code:
      type: string(60)
    notes:
      type: string
  relations:
    AlAmsStd:
      local: id
      foreign: al_std_series_id
      type: many
AlcheckAnalysis:
  tableName: alcheck_analysis
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    sample_id:
      type: integer
      unsigned: true
    alcheck_batch_id:
      type: integer
      unsigned: true
      default: '0'
      notnull: true
    number_within_batch:
      type: integer
      unsigned: true
      default: '0'
      notnull: true
    sample_name:
      type: string
      notnull: true
    bkr_number:
      type: string
      notnull: true
    wt_bkr_tare:
      type: double(53,30)
      default: '0'
      notnull: true
    flag_bkr_tare_avg:
      type: integer
      unsigned: true
      default: '0'
      notnull: true
    wt_bkr_sample:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_bkr_soln:
      type: double(53,30)
      default: '0'
    icp_al:
      type: double(53,30)
      default: '0'
    icp_ba:
      type: double(53,30)
      default: '0'
    icp_be:
      type: double(53,30)
      default: '0'
    icp_ca:
      type: double(53,30)
      default: '0'
    icp_fe:
      type: double(53,30)
      default: '0'
    icp_k:
      type: double(53,30)
      default: '0'
    icp_mg:
      type: double(53,30)
      default: '0'
    icp_mn:
      type: double(53,30)
      default: '0'
    icp_na:
      type: double(53,30)
      default: '0'
    icp_ti:
      type: double(53,30)
      default: '0'
    addl_dil_factor:
      type: double(53,30)
      default: '1'
      notnull: true
    notes:
      type: string
  relations:
    Sample:
      local: sample_id
      foreign: id
      type: one
    AlcheckBatch:
      local: alcheck_batch_id
      foreign: id
      type: one
AlcheckBatch:
  tableName: alcheck_batch
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    owner:
      type: string
    prep_date:
      type: date(25)
    icp_date:
      type: date(25)
    description:
      type: string
    notes:
      type: string
  relations:
    AlcheckAnalysis:
      local: id
      foreign: alcheck_batch_id
      type: many
AmsCurrent:
  tableName: ams_current
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    current:
      type: double(53,30)
    be_ams_id:
      type: integer
      unsigned: true
    al_ams_id:
      type: integer
      unsigned: true
  relations:
    BeAms:
      local: be_ams_id
      foreign: id
      type: one
    AlAms:
      local: al_ams_id
      foreign: id
      type: one
AmsLab:
  tableName: ams_lab
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(255)
      default: ''
      notnull: true
    full_name:
      type: string(700)
  relations:
    AlAms:
      local: id
      foreign: ams_lab_id
      type: many
    BeAms:
      local: id
      foreign: ams_lab_id
      type: many
Analysis:
  tableName: analysis
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    batch_id:
      type: integer
      unsigned: true
      default: '0'
      notnull: true
    sample_id:
      type: integer
      unsigned: true
    number_within_batch:
      type: integer
      default: '0'
      notnull: true
    sample_name:
      type: string
      notnull: true
    sample_type:
      type: string
      notnull: true
    diss_bottle_id:
      type: integer
      unsigned: true
    diss_bottle_number:
      type: string
      notnull: true
    wt_diss_bottle_tare:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_diss_bottle_sample:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_be_carrier:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_al_carrier:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_diss_bottle_total:
      type: double(53,30)
      default: '0'
      notnull: true
    notes:
      type: string
      notnull: true
  relations:
    Batch:
      local: batch_id
      foreign: id
      type: one
    Sample:
      local: sample_id
      foreign: id
      type: one
    DissBottle:
      local: diss_bottle_id
      foreign: id
      type: one
    AlAms:
      local: id
      foreign: analysis_id
      type: many
    BeAms:
      local: id
      foreign: analysis_id
      type: many
    Split:
      local: id
      foreign: analysis_id
      type: many
Batch:
  tableName: batch
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    al_carrier_id:
      type: integer
      unsigned: true
    be_carrier_id:
      type: integer
      unsigned: true
    owner:
      type: string
    description:
      type: string
    start_date:
      type: date(25)
      default: '0000-00-00'
      notnull: true
    split_date:
      type: date(25)
      default: '0000-00-00'
      notnull: true
    icp_date:
      type: date(25)
      default: '0000-00-00'
      notnull: true
    be_carrier_name:
      type: string
      notnull: true
    wt_be_carrier_init:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_be_carrier_final:
      type: double(53,30)
      default: '0'
      notnull: true
    al_carrier_name:
      type: string
      notnull: true
    wt_al_carrier_init:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_al_carrier_final:
      type: double(53,30)
      default: '0'
      notnull: true
    notes:
      type: string
    completed:
      type: enum(1)
      values:
        - y
        - n
      default: n
      notnull: true
    spreadsheet_name:
      type: string
    csv_name:
      type: string
  relations:
    AlCarrier:
      local: al_carrier_id
      foreign: id
      type: one
    BeCarrier:
      local: be_carrier_id
      foreign: id
      type: one
    Analysis:
      local: id
      foreign: batch_id
      type: many
BeAms:
  tableName: be_ams
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    analysis_id:
      type: integer
      unsigned: true
    be_ams_std_id:
      type: integer
      unsigned: true
    ams_lab_id:
      type: integer
      unsigned: true
    date:
      type: date(25)
    lab_num:
      type: string(255)
    r_to_rstd:
      type: double(53,30)
    interror:
      type: double(53,30)
    exterror:
      type: double(53,30)
    truefrac:
      type: double(53,30)
    notes:
      type: string(700)
  relations:
    Analysis:
      local: analysis_id
      foreign: id
      type: one
    BeAmsStd:
      local: be_ams_std_id
      foreign: id
      type: one
    AmsLab:
      local: ams_lab_id
      foreign: id
      type: one
    AmsCurrent:
      local: id
      foreign: be_ams_id
      type: many
BeAmsStd:
  tableName: be_ams_std
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(255)
    be_std_series_id:
      type: integer
      unsigned: true
    r10to9:
      type: double(53,30)
    error:
      type: double(53,30)
    notes:
      type: string
  relations:
    BeStdSeries:
      local: be_std_series_id
      foreign: id
      type: one
    BeAms:
      local: id
      foreign: be_ams_std_id
      type: many
BeCarrier:
  tableName: be_carrier
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string
      notnull: true
    be_conc:
      type: double(53,30)
    del_be_conc:
      type: double(53,30)
    al_conc:
      type: double(53,30)
    del_al_conc:
      type: double(53,30)
    r10to9:
      type: double(53,30)
    r10to9_error:
      type: double(53,30)
    in_service_date:
      type: date(25)
    mfg_lot_no:
      type: string
    owner:
      type: string
    notes:
      type: string
    in_use:
      type: string
  relations:
    Batch:
      local: id
      foreign: be_carrier_id
      type: many
BeStdSeries:
  tableName: be_std_series
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    code:
      type: string(60)
    notes:
      type: string
  relations:
    BeAmsStd:
      local: id
      foreign: be_std_series_id
      type: many
DissBottle:
  tableName: diss_bottle
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    bottle_number:
      type: string
  relations:
    Analysis:
      local: id
      foreign: diss_bottle_id
      type: many
IcpRun:
  tableName: icp_run
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    split_id:
      type: integer
      unsigned: true
    run_num:
      type: integer
      unsigned: true
      default: '1'
      notnull: true
    al_result:
      type: double(53,30)
      default: '0'
      notnull: true
    be_result:
      type: double(53,30)
      default: '0'
      notnull: true
    use_al:
      type: enum(1)
      values:
        - y
        - n
      default: y
      notnull: true
    use_be:
      type: enum(1)
      values:
        - y
        - n
      default: y
      notnull: true
  relations:
    Split:
      local: split_id
      foreign: id
      type: one
Project:
  tableName: project
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    date_added:
      type: timestamp(25)
    description:
      type: string
  relations:
    ProjectSample:
      local: id
      foreign: project_id
      type: many
    Sample:
      refClass: ProjectSample
      local: project_id
      foreign: sample_id
      type: many
ProjectSample:
  tableName: project_sample
  columns:
    project_id:
      type: integer
      unsigned: true
      primary: true
    sample_id:
      type: integer
      unsigned: true
      primary: true
  relations:
    Project:
      local: project_id
      foreign: id
      type: one
    Sample:
      local: sample_id
      foreign: id
      type: one
Sample:
  tableName: sample
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(255)
      default: ''
      notnull: true
    latitude:
      type: double(53,30)
    longitude:
      type: double(53,30)
    altitude:
      type: double(53,30)
    antarctic:
      type: integer
      default: '0'
      notnull: true
    shield_factor:
      type: double(53,30)
    depth_top:
      type: double(53,30)
    depth_bottom:
      type: double(53,30)
    density:
      type: double(53,30)
    erosion_rate:
      type: double(53,30)
    notes:
      type: string
  relations:
    AlcheckAnalysis:
      local: id
      foreign: sample_id
      type: many
    Analysis:
      local: id
      foreign: sample_id
      type: many
    ProjectSample:
      local: id
      foreign: sample_id
      type: many
    SilCl36Analysis:
      local: id
      foreign: sample_id
      type: many
    Project:
      refClass: ProjectSample
      local: sample_id
      foreign: project_id
      type: many
SilCl36Analysis:
  tableName: sil_cl36_analysis
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    sample_id:
      type: integer
      unsigned: true
    sample_name:
      type: string(255)
      default: ''
      notnull: true
    cl36_batch_id:
      type: integer
      unsigned: true
    calib_id:
      type: integer
      unsigned: true
    cl37_spike_id:
      type: integer
      unsigned: true
    sample_type:
      type: enum(6)
      values:
        - SAMPLE
        - CALIB
        - BLANK
      default: SAMPLE
      notnull: true
    wt_spike:
      type: double(53,30)
    wt_bkr_tare:
      type: double(53,30)
    wt_bkr_sample:
      type: double(53,30)
  relations:
    Sample:
      local: sample_id
      foreign: id
      type: one
SilCl36Batch:
  tableName: sil_cl36_batch
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    owner:
      type: string(60)
    cl_carrier_id:
      type: integer
Split:
  tableName: split
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    analysis_id:
      type: integer
      unsigned: true
      notnull: true
    split_bkr_id:
      type: integer
      unsigned: true
    split_num:
      type: integer
      unsigned: true
      default: '1'
      notnull: true
    split_bkr_name:
      type: string
    wt_split_bkr_tare:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_split_bkr_split:
      type: double(53,30)
      default: '0'
      notnull: true
    wt_split_bkr_icp:
      type: double(53,30)
      default: '0'
      notnull: true
  relations:
    Analysis:
      local: analysis_id
      foreign: id
      type: one
    SplitBkr:
      local: split_bkr_id
      foreign: id
      type: one
    IcpRun:
      local: id
      foreign: split_id
      type: many
SplitBkr:
  tableName: split_bkr
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    bkr_number:
      type: string
  relations:
    Split:
      local: id
      foreign: split_bkr_id
      type: many
